# Generated by Django 4.2.25 on 2025-11-04 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareddelivery',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_deliveries', to='orders.order'),
        ),
        migrations.AddField(
            model_name='shareddelivery',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'VENDOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='shared_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logisticscostshare',
            name='shared_delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_breakdown', to='logistics.shareddelivery'),
        ),
        migrations.AddField(
            model_name='deliveryroute',
            name='delivery_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='logistics.deliverygroup'),
        ),
        migrations.AlterUniqueTogether(
            name='shareddelivery',
            unique_together={('vendor', 'delivery_group', 'order')},
        ),
    ]
