# Generated by Django 4.2.25 on 2025-11-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_add_supplier_features'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rawmaterial',
            new_name='suppliers_r_approva_5df450_idx',
            old_name='suppliers_r_approva_idx',
        ),
        migrations.RenameIndex(
            model_name='rawmaterialpurchase',
            new_name='suppliers_r_vendor__533e7e_idx',
            old_name='suppliers_r_vendor__idx',
        ),
        migrations.RenameIndex(
            model_name='rawmaterialpurchase',
            new_name='suppliers_r_supplie_8ddd55_idx',
            old_name='suppliers_r_supplie_idx',
        ),
        migrations.RenameIndex(
            model_name='rawmaterialpurchase',
            new_name='suppliers_r_payment_b0296c_idx',
            old_name='suppliers_r_payment_idx',
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
