# Generated by Django 4.2.25 on 2025-11-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectproposal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='expense_breakdown',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='timeline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
