# Generated by Django 4.2.25 on 2025-11-04 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
        ('loyalty', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardredemption',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_redemptions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='loyalty.reward'),
        ),
        migrations.AddField(
            model_name='reward',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='projects.communityproject'),
        ),
        migrations.AddField(
            model_name='reward',
            name='special_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='products.product'),
        ),
        migrations.AddField(
            model_name='loyaltypointstransaction',
            name='loyalty_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltyaccount'),
        ),
        migrations.AddField(
            model_name='loyaltypointstransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='loyaltypointstransaction',
            name='reward_redemption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='loyalty.rewardredemption'),
        ),
        migrations.AddField(
            model_name='loyaltypointstransaction',
            name='social_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='loyalty.socialmediapost'),
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='customer',
            field=models.OneToOneField(limit_choices_to={'user_type': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loyaltypointstransaction',
            index=models.Index(fields=['loyalty_account', 'created_at'], name='loyalty_loy_loyalty_557968_idx'),
        ),
    ]
