# Generated by Django 4.2.25 on 2025-11-04 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suppliers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGapAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('unavailable_product_count', models.PositiveIntegerField(default=0)),
                ('job_posting_count', models.PositiveIntegerField(default=0)),
                ('search_demand_count', models.PositiveIntegerField(default=0)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('estimated_impact', models.TextField(blank=True, null=True)),
                ('recommended_actions', models.TextField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('last_analyzed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_gaps', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Skill Gap Analyses',
                'ordering': ['-severity', '-unavailable_product_count'],
            },
        ),
        migrations.CreateModel(
            name='SearchTrendAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=500)),
                ('search_count', models.PositiveIntegerField(default=0)),
                ('results_returned', models.PositiveIntegerField(default=0)),
                ('is_product_available', models.BooleanField(default=False)),
                ('unavailable_count', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('potential_skill_gap', models.BooleanField(default=False)),
                ('skill_gap_reason', models.TextField(blank=True, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Search Trend Analytics',
                'ordering': ['-unavailable_count', '-search_count'],
                'indexes': [models.Index(fields=['potential_skill_gap', 'unavailable_count'], name='ministries__potenti_2a1e2c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MinistryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('JOB_POSTINGS', 'Job Postings Summary'), ('PROJECT_PROGRESS', 'Project Progress'), ('MATERIAL_USAGE', 'Material Usage Analysis'), ('SEARCH_TRENDS', 'Search Trends'), ('SKILL_GAPS', 'Skill Gap Analysis'), ('BRAND_GROWTH', 'Local Brand Growth'), ('COMPREHENSIVE', 'Comprehensive Report')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('report_data', models.JSONField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='ministry_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ministry', models.ForeignKey(limit_choices_to={'user_type': 'MINISTRY'}, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MinistryDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_job_postings', models.BooleanField(default=True)),
                ('show_project_progress', models.BooleanField(default=True)),
                ('show_material_analytics', models.BooleanField(default=True)),
                ('show_search_trends', models.BooleanField(default=True)),
                ('show_skill_gaps', models.BooleanField(default=True)),
                ('show_brand_growth', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ministry', models.OneToOneField(limit_choices_to={'user_type': 'MINISTRY'}, on_delete=django.db.models.deletion.CASCADE, related_name='ministry_dashboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ministry_dashboards',
            },
        ),
        migrations.CreateModel(
            name='MaterialUsageAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('total_quantity_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('products_using', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_type', models.CharField(default='monthly', max_length=20)),
                ('usage_trend', models.CharField(blank=True, max_length=20, null=True)),
                ('growth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_analytics', to='suppliers.rawmaterial')),
            ],
            options={
                'verbose_name_plural': 'Material Usage Analytics',
                'ordering': ['-times_used'],
                'unique_together': {('material', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='LocalBrandGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('revenue_growth_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('order_growth_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('active_products', models.PositiveIntegerField(default=0)),
                ('new_products_count', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('vendor_count', models.PositiveIntegerField(default=0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_metrics', to='products.brand')),
            ],
            options={
                'verbose_name_plural': 'Local Brand Growth Metrics',
                'ordering': ['-revenue_growth_percentage'],
                'unique_together': {('brand', 'period_start', 'period_end')},
            },
        ),
    ]
