# Generated by Django 4.2.25 on 2025-11-19 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_alter_category_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('TWITTER', 'Twitter'), ('WHATSAPP_BUSINESS', 'WhatsApp Business')], max_length=20)),
                ('account_name', models.CharField(help_text='Page/Account name', max_length=200)),
                ('account_id', models.CharField(help_text='Platform account ID', max_length=200)),
                ('account_username', models.CharField(blank=True, max_length=200, null=True)),
                ('access_token', models.TextField(help_text='OAuth access token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('auto_post', models.BooleanField(default=False, help_text='Auto-post new products')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Token Expired'), ('DISCONNECTED', 'Disconnected'), ('ERROR', 'Error')], default='ACTIVE', max_length=20)),
                ('total_posts', models.PositiveIntegerField(default=0)),
                ('last_post_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(limit_choices_to={'user_type': 'VENDOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='social_media_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Media Account',
                'verbose_name_plural': 'Social Media Accounts',
                'ordering': ['-connected_at'],
                'unique_together': {('vendor', 'platform', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='SocialMediaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('TWITTER', 'Twitter'), ('WHATSAPP_BUSINESS', 'WhatsApp Business')], max_length=20)),
                ('name', models.CharField(help_text='Template name for reference', max_length=100)),
                ('template_text', models.TextField(help_text='Use {product_name}, {price}, {description}, {url} as placeholders')),
                ('hashtags', models.TextField(blank=True, help_text='Comma-separated hashtags (without #)', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Use as default for this platform')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(limit_choices_to={'user_type': 'VENDOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='social_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_posts', models.PositiveIntegerField(default=0)),
                ('successful_posts', models.PositiveIntegerField(default=0)),
                ('failed_posts', models.PositiveIntegerField(default=0)),
                ('total_likes', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('total_shares', models.PositiveIntegerField(default=0)),
                ('total_reach', models.PositiveIntegerField(default=0)),
                ('clicks_to_website', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='social_media.socialmediaaccount')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Media Analytics',
                'verbose_name_plural': 'Social Media Analytics',
                'ordering': ['-month'],
                'unique_together': {('vendor', 'social_account', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField()),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('POSTED', 'Posted'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('post_id', models.CharField(blank=True, max_length=200, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='products.product')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='social_media.socialmediaaccount')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='social_medi_status_6ac6ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductSocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(blank=True, help_text='Platform post ID', max_length=200, null=True)),
                ('post_url', models.URLField(blank=True, help_text='Link to post', null=True)),
                ('post_text', models.TextField(help_text='Post caption/text')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('POSTED', 'Posted Successfully'), ('FAILED', 'Failed'), ('DELETED', 'Deleted')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('reach', models.PositiveIntegerField(default=0, help_text='Number of people reached')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_social_posts', to='products.product')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_posts', to='social_media.socialmediaaccount')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_social_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'status'], name='social_medi_vendor__f118dd_idx'), models.Index(fields=['product', 'social_account'], name='social_medi_product_7487f9_idx')],
            },
        ),
    ]
