# Generated by Django 4.2.25 on 2025-11-19 13:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0003_rename_suppliers_r_approva_idx_suppliers_r_approva_5df450_idx_and_more'),
        ('products', '0007_alter_category_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_size', models.DecimalField(decimal_places=2, default=1, help_text='How many units this recipe makes', max_digits=10)),
                ('production_time_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Time needed to produce one batch', max_digits=6, null=True)),
                ('total_material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('labor_cost_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='Optional labor cost', max_digits=10)),
                ('overhead_cost_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='Optional overhead', max_digits=10)),
                ('total_cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=50, help_text='Suggested markup %', max_digits=5)),
                ('suggested_selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('instructions', models.TextField(blank=True, help_text='Production instructions', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='products.product')),
                ('vendor', models.ForeignKey(limit_choices_to={'user_type': 'VENDOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bill of Materials',
                'verbose_name_plural': 'Bills of Materials',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mo_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('quantity_to_produce', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_produced', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_approved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_rejected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready to Start'), ('IN_PROGRESS', 'In Progress'), ('QUALITY_CHECK', 'Quality Check'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('production_notes', models.TextField(blank=True, null=True)),
                ('local_materials_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='manufacturing.billofmaterials')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_orders', to='products.product')),
                ('vendor', models.ForeignKey(limit_choices_to={'user_type': 'VENDOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_checked', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_approved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_rejected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REWORK', 'Needs Rework')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checks_performed', to=settings.AUTH_USER_MODEL)),
                ('manufacturing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='manufacturing.manufacturingorder')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, help_text='e.g., Craftsman, Assembly, Packaging', max_length=100, null=True)),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('work_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='manufacturing.manufacturingorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_work', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-work_date'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_units_produced', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_production_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('local_materials_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_workers', models.PositiveIntegerField(default=0)),
                ('total_hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_wages_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('community_contribution', models.DecimalField(decimal_places=2, default=0, help_text='1% of production value', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Manufacturing Analytics',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(help_text='kg, meters, pieces, etc.', max_length=50)),
                ('notes', models.CharField(blank=True, help_text='e.g., "Cut into 10cm pieces"', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='manufacturing.billofmaterials')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_usage', to='suppliers.rawmaterial')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='manufacturingorder',
            index=models.Index(fields=['vendor', 'status'], name='manufacturi_vendor__fd3d03_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturingorder',
            index=models.Index(fields=['status', 'scheduled_date'], name='manufacturi_status_15ca90_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='manufacturinganalytics',
            unique_together={('vendor', 'month')},
        ),
    ]
