# Generated by Django 4.2.25 on 2025-11-04 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
        ('projects', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votinghistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voting_history', to='orders.order'),
        ),
        migrations.AddField(
            model_name='votinghistory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_history', to='projects.communityproject'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'CUSTOMER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerimpactmetrics',
            name='customer',
            field=models.OneToOneField(limit_choices_to={'user_type': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='impact_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerdashboard',
            name='customer',
            field=models.OneToOneField(limit_choices_to={'user_type': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_dashboard', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerdashboard',
            name='default_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_customers', to='projects.communityproject'),
        ),
        migrations.AddField(
            model_name='customerdashboard',
            name='last_viewed_products',
            field=models.ManyToManyField(blank=True, related_name='viewed_by_customers', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['customer', 'created_at'], name='customers_s_custome_78e9b7_idx'),
        ),
    ]
