# Generated by Django 4.2.25 on 2025-11-11 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_reviewhelpfulvote_reviewphoto_and_more'),
        ('projects', '0002_projectproposal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_initial'),
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_referrals', models.PositiveIntegerField(default=0)),
                ('successful_signups', models.PositiveIntegerField(default=0)),
                ('successful_purchases', models.PositiveIntegerField(default=0)),
                ('total_points_earned', models.PositiveIntegerField(default=0)),
                ('total_rewards_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referrer', models.ForeignKey(limit_choices_to={'user_type': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code_used', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Signup'), ('SIGNED_UP', 'Signed Up'), ('FIRST_PURCHASE', 'First Purchase Made'), ('REWARDED', 'Reward Given')], default='PENDING', max_length=20)),
                ('referrer_points_awarded', models.PositiveIntegerField(default=0)),
                ('referred_points_awarded', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_up_at', models.DateTimeField(blank=True, null=True)),
                ('first_purchase_at', models.DateTimeField(blank=True, null=True)),
                ('first_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_orders', to='orders.order')),
                ('referral_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_instances', to='customers.referralprogram')),
                ('referred_user', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'CUSTOMER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('testimonial', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5)),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(limit_choices_to={'user_type': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='orders.order')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_testimonials', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(limit_choices_to={'user_type': 'VENDOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_testimonials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_type', models.CharField(choices=[('PRODUCT', 'Product'), ('PROJECT', 'Project'), ('VENDOR', 'Vendor')], max_length=20)),
                ('platform', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('WHATSAPP', 'WhatsApp'), ('LINKEDIN', 'LinkedIn'), ('EMAIL', 'Email'), ('OTHER', 'Other')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_shares', to='products.product')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_shares', to='projects.communityproject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_shares', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'VENDOR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_social_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['share_type', 'platform', 'created_at'], name='customers_s_share_t_b98ac8_idx'), models.Index(fields=['product', 'created_at'], name='customers_s_product_41a8dc_idx'), models.Index(fields=['project', 'created_at'], name='customers_s_project_cb876d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='referralprogram',
            index=models.Index(fields=['referral_code'], name='customers_r_referra_822e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='referralprogram',
            index=models.Index(fields=['referrer', 'is_active'], name='customers_r_referre_763066_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referral_code_used', 'status'], name='customers_r_referra_85500f_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referral_program', 'status'], name='customers_r_referra_383597_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together={('referral_program', 'referred_user')},
        ),
        migrations.AddIndex(
            model_name='customertestimonial',
            index=models.Index(fields=['vendor', 'status', 'is_featured'], name='customers_c_vendor__ddd48e_idx'),
        ),
        migrations.AddIndex(
            model_name='customertestimonial',
            index=models.Index(fields=['customer', 'vendor'], name='customers_c_custome_e3763b_idx'),
        ),
    ]
