# Generated by Django 4.2.25 on 2025-11-12 14:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0005_vendorsubscription_projectnotificationsubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('SUPPORT', 'Support'), ('PURCHASE', 'Purchase'), ('PROJECT', 'Project'), ('COMMUNITY', 'Community'), ('CHALLENGE', 'Challenge')], max_length=30)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(default='#be8400', max_length=20)),
                ('points_reward', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('criteria_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommunityChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('PROJECT', 'Project Contributions'), ('PURCHASE', 'Purchases'), ('COMMUNITY', 'Community')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reward_points', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_challenges', to='customers.achievementbadge')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ImpactLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('DIAMOND', 'Diamond')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_points', models.PositiveIntegerField()),
                ('badge_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(default='#be8400', max_length=20)),
                ('perks', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['min_points'],
            },
        ),
        migrations.AddField(
            model_name='customerimpactmetrics',
            name='impact_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerimpactmetrics',
            name='total_badges_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerimpactmetrics',
            name='current_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.impactlevel'),
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_type', models.CharField(choices=[('PROJECT_CONTRIBUTION', 'Project Contribution'), ('IMPACT_POINTS', 'Impact Points'), ('PURCHASES', 'Purchases')], max_length=40)),
                ('period', models.CharField(choices=[('ALL_TIME', 'All Time'), ('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly')], default='ALL_TIME', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(limit_choices_to={'user_type': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['leaderboard_type', 'period', 'rank'],
                'indexes': [models.Index(fields=['leaderboard_type', 'period', 'rank'], name='customers_l_leaderb_a156a3_idx')],
                'unique_together': {('customer', 'leaderboard_type', 'period')},
            },
        ),
        migrations.CreateModel(
            name='CustomerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('EARNED', 'Earned')], default='IN_PROGRESS', max_length=20)),
                ('progress', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5)),
                ('progress_value', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('earned_at', models.DateTimeField(blank=True, null=True)),
                ('notify_user', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_achievements', to='customers.achievementbadge')),
                ('customer', models.ForeignKey(limit_choices_to={'user_type': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at', '-created_at'],
                'indexes': [models.Index(fields=['customer', 'status'], name='customers_c_custome_287dc3_idx')],
                'unique_together': {('customer', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='CommunityChallengeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_value', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='customers.communitychallenge')),
                ('customer', models.ForeignKey(limit_choices_to={'user_type': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-contribution_value'],
                'indexes': [models.Index(fields=['challenge', 'completed'], name='customers_c_challen_201fbf_idx')],
                'unique_together': {('challenge', 'customer')},
            },
        ),
        migrations.AddIndex(
            model_name='communitychallenge',
            index=models.Index(fields=['challenge_type', 'is_active'], name='customers_c_challen_383255_idx'),
        ),
    ]
