# Generated by Django 4.2.25 on 2025-11-21 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0006_achievementbadge_communitychallenge_impactlevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
