# Generated by Django 4.2.25 on 2025-11-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendorprofile_participate_in_projects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('badge_type', models.CharField(choices=[('TOP_SELLER', 'Top Seller'), ('LOCAL_CHAMPION', 'Local Champion'), ('ECO_FRIENDLY', 'Eco-Friendly'), ('FAST_RESPONDER', 'Fast Responder'), ('HIGH_RATED', 'High Rated'), ('VERIFIED', 'Verified'), ('COMMUNITY_HERO', 'Community Hero'), ('TRUSTED_VENDOR', 'Trusted Vendor')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(default='#be8400', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('min_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('min_reviews', models.PositiveIntegerField(blank=True, null=True)),
                ('min_sales', models.PositiveIntegerField(blank=True, null=True)),
                ('min_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_response_time_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('min_local_products', models.PositiveIntegerField(blank=True, null=True)),
                ('min_eco_products', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='average_response_time_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='overall_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='ratings_last_calculated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='vendors', to='vendors.vendorbadge'),
        ),
    ]
