# Generated by Django 4.2.25 on 2025-11-12 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0003_vendorbadge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='delivery_base_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='delivery_free_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='delivery_free_radius_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='delivery_per_km_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='VendorPaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('CASH_ON_DELIVERY', 'Cash on Delivery'), ('ECOCASH', 'EcoCash'), ('ONEMONEY', 'OneMoney'), ('INBUCKS', 'InBucks')], max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(limit_choices_to={'user_type': 'VENDOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_options', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['vendor', 'payment_type'],
                'unique_together': {('vendor', 'payment_type')},
            },
        ),
    ]
