# Generated by Django 4.2.25 on 2025-11-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendorprofile_delivery_base_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpaymentoption',
            name='merchant_name',
            field=models.CharField(blank=True, help_text='Full name or merchant name as it appears when transferring money (required for mobile wallets)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpaymentoption',
            name='payment_type',
            field=models.CharField(choices=[('CASH_ON_DELIVERY', 'Cash on Delivery'), ('ECOCASH', 'EcoCash'), ('ONEMONEY', 'OneMoney'), ('INNBUCKS', 'InnBucks')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vendorpaymentoption',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for receiving payments', max_length=50, null=True),
        ),
    ]
