# Generated by Django 4.2.25 on 2025-11-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendorpaymentoption_merchant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='location_address',
            field=models.TextField(blank=True, help_text='Full address for delivery distance calculation', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for distance calculation (optional)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for distance calculation (optional)', max_digits=9, null=True),
        ),
    ]
