# Generated by Django 4.2.25 on 2025-11-19 12:12

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0006_vendorprofile_location_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='harare_beyond_radius_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='harare_radius_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='harare_within_radius_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='VendorDeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('HARARE', 'Harare (General)'), ('MUTARE', 'Mutare'), ('BULAWAYO', 'Bulawayo'), ('KADOMA', 'Kadoma'), ('NORTON', 'Norton'), ('CHEGUTU', 'Chegutu'), ('VICTORIA_FALLS', 'Victoria Falls'), ('KWEKWE', 'Kwekwe'), ('GWERU', 'Gweru'), ('MASVINGO', 'Masvingo'), ('BINDURA', 'Bindura'), ('CHINHOYI', 'Chinhoyi'), ('MAZOE', 'Mazowe'), ('CHIVHU', 'Chivhu'), ('CHIREDZI', 'Chiredzi'), ('CHITUNGWIZA', 'Chitungwiza')], max_length=50)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(limit_choices_to={'user_type': 'VENDOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['city'],
                'unique_together': {('vendor', 'city')},
            },
        ),
    ]
