# Generated by Django 4.2.25 on 2025-11-21 20:14

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_alter_category_options'),
        ('vendors', '0009_salereceipt_vendordiscussion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "Black Friday Mega Sale", "Christmas Special"', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the promotion')),
                ('style', models.CharField(choices=[('hot-deal', '🔥 Hot Deal'), ('limited-time', '⏰ Limited Time'), ('seasonal', '🎄 Seasonal'), ('flash-sale', '⚡ Flash Sale'), ('clearance', '🏷️ Clearance'), ('special-offer', '⭐ Special Offer'), ('black-friday', '🛍️ Black Friday'), ('christmas', '🎅 Christmas'), ('new-year', '🎉 New Year'), ('easter', '🐰 Easter'), ('valentines', "💝 Valentine's"), ('mothers-day', "👩 Mother's Day"), ('fathers-day', "👨 Father's Day"), ('independence', '🇿🇼 Independence Day'), ('custom', '✨ Custom')], default='special-offer', help_text='Visual style/badge for the promotion', max_length=50)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage (e.g., 25 for 25% off)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('99.99'))])),
                ('start_date', models.DateTimeField(help_text='When the promotion starts')),
                ('end_date', models.DateTimeField(help_text='When the promotion ends')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('PAUSED', 'Paused')], default='DRAFT', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Manual toggle to activate/deactivate')),
                ('show_badge', models.BooleanField(default=True, help_text='Show promotion badge on products')),
                ('show_countdown', models.BooleanField(default=False, help_text='Show countdown timer')),
                ('featured', models.BooleanField(default=False, help_text='Feature this promotion on vendor page')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of views')),
                ('click_count', models.PositiveIntegerField(default=0, help_text='Number of clicks')),
                ('conversion_count', models.PositiveIntegerField(default=0, help_text='Number of sales')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue from this promotion', max_digits=12)),
                ('terms', models.TextField(blank=True, help_text='Terms and conditions for this promotion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='vendors.vendorcompany')),
                ('vendor', models.ForeignKey(limit_choices_to={'user_type': 'VENDOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Original product price', max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, help_text='Price after discount', max_digits=10)),
                ('savings_amount', models.DecimalField(decimal_places=2, help_text='Amount saved', max_digits=10)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_links', to='products.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='vendors.promotion')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('sales', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='vendors.promotion')),
            ],
            options={
                'verbose_name_plural': 'Promotion Analytics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['promotion', 'date'], name='vendors_pro_promoti_8d891c_idx')],
                'unique_together': {('promotion', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['vendor', 'status'], name='vendors_pro_vendor__ffd579_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['start_date', 'end_date'], name='vendors_pro_start_d_8f53f8_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['status', 'is_active'], name='vendors_pro_status_e9d20b_idx'),
        ),
        migrations.AddIndex(
            model_name='productpromotion',
            index=models.Index(fields=['promotion', 'product'], name='vendors_pro_promoti_9ce04a_idx'),
        ),
        migrations.AddIndex(
            model_name='productpromotion',
            index=models.Index(fields=['product'], name='vendors_pro_product_f0dbd0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productpromotion',
            unique_together={('promotion', 'product')},
        ),
    ]
