# Generated by Django 4.2.25 on 2025-11-12 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPaymentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('CASH_ON_DELIVERY', 'Cash on Delivery'), ('ECOCASH', 'EcoCash'), ('ONEMONEY', 'OneMoney'), ('INBUCKS', 'InBucks')], max_length=30)),
                ('payment_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('payer_name', models.CharField(help_text='Name that appears on the payment transaction', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='payments/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('ACKNOWLEDGED', 'Acknowledged by Vendor')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_submissions', to='orders.order')),
                ('vendor', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'VENDOR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
