# Generated by Django 4.2.25 on 2025-11-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderpaymentsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpaymentsubmission',
            name='payment_type',
            field=models.CharField(choices=[('CASH_ON_DELIVERY', 'Cash on Delivery'), ('ECOCASH', 'EcoCash'), ('ONEMONEY', 'OneMoney'), ('INNBUCKS', 'InnBucks')], max_length=30),
        ),
    ]
