# Generated by Django 4.2.25 on 2025-11-21 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_order', models.BooleanField(default=True)),
                ('notify_payment_received', models.BooleanField(default=True)),
                ('notify_new_review', models.BooleanField(default=True)),
                ('notify_low_stock', models.BooleanField(default=True)),
                ('notify_new_supplier', models.BooleanField(default=True)),
                ('notify_event_created', models.BooleanField(default=True)),
                ('notify_promotion_ending', models.BooleanField(default=True)),
                ('notify_discussion_reply', models.BooleanField(default=True)),
                ('notify_manufacturing', models.BooleanField(default=True)),
                ('notify_order_status', models.BooleanField(default=True)),
                ('notify_payment_status', models.BooleanField(default=True)),
                ('notify_product_recommendations', models.BooleanField(default=True)),
                ('notify_price_drops', models.BooleanField(default=True)),
                ('notify_back_in_stock', models.BooleanField(default=True)),
                ('notify_new_projects', models.BooleanField(default=True)),
                ('notify_wishlist_sales', models.BooleanField(default=True)),
                ('notify_loyalty_rewards', models.BooleanField(default=True)),
                ('send_email_notifications', models.BooleanField(default=True)),
                ('email_frequency', models.CharField(choices=[('INSTANT', 'Instant'), ('DAILY', 'Daily Digest'), ('WEEKLY', 'Weekly Summary'), ('NEVER', 'Never')], default='INSTANT', max_length=20)),
                ('enable_push_notifications', models.BooleanField(default=True)),
                ('enable_quiet_hours', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='e.g., 22:00', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='e.g., 08:00', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notification_type', models.CharField(choices=[('NEW_ORDER', '🛒 New Order'), ('ORDER_CANCELLED', '❌ Order Cancelled'), ('PAYMENT_RECEIVED', '💰 Payment Received'), ('NEW_REVIEW', '⭐ New Review'), ('LOW_STOCK', '📦 Low Stock Alert'), ('NEW_SUPPLIER', '🏭 New Supplier Available'), ('SUPPLIER_APPROVED', '✅ Supplier Material Approved'), ('EVENT_CREATED', '📅 New Event Created'), ('PROMOTION_ENDING', '⏰ Promotion Ending Soon'), ('NEW_MESSAGE', '💬 New Message'), ('DISCUSSION_REPLY', '💭 Discussion Reply'), ('ACCOUNT_VERIFIED', '✅ Account Verified'), ('BADGE_EARNED', '🏆 Badge Earned'), ('MANUFACTURING_COMPLETE', '🏭 Manufacturing Complete'), ('QUALITY_CHECK_FAILED', '⚠️ Quality Check Failed'), ('ORDER_CONFIRMED', '✅ Order Confirmed'), ('ORDER_SHIPPED', '🚚 Order Shipped'), ('ORDER_DELIVERED', '📦 Order Delivered'), ('PAYMENT_PROCESSED', '💳 Payment Processed'), ('NEW_PRODUCT_RECOMMENDATION', '✨ New Product You May Like'), ('PRICE_DROP', '💰 Price Drop Alert'), ('BACK_IN_STOCK', '📦 Back in Stock'), ('NEW_PROJECT', '🌍 New Community Project'), ('WISHLIST_SALE', '🎉 Wishlist Item on Sale'), ('LOYALTY_REWARD', '🎁 Loyalty Reward Earned'), ('VENDOR_RESPONSE', '💬 Vendor Responded'), ('REVIEW_HELPFUL', '👍 Review Marked Helpful'), ('NEW_FOLLOWER', '👤 New Follower')], max_length=50)),
                ('message_template', models.TextField()),
                ('recipient_type', models.CharField(choices=[('ALL_VENDORS', 'All Vendors'), ('ALL_CUSTOMERS', 'All Customers'), ('SPECIFIC_USERS', 'Specific Users')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notification_batches', to=settings.AUTH_USER_MODEL)),
                ('specific_users', models.ManyToManyField(blank=True, related_name='batch_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Batch',
                'verbose_name_plural': 'Notification Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('NEW_ORDER', '🛒 New Order'), ('ORDER_CANCELLED', '❌ Order Cancelled'), ('PAYMENT_RECEIVED', '💰 Payment Received'), ('NEW_REVIEW', '⭐ New Review'), ('LOW_STOCK', '📦 Low Stock Alert'), ('NEW_SUPPLIER', '🏭 New Supplier Available'), ('SUPPLIER_APPROVED', '✅ Supplier Material Approved'), ('EVENT_CREATED', '📅 New Event Created'), ('PROMOTION_ENDING', '⏰ Promotion Ending Soon'), ('NEW_MESSAGE', '💬 New Message'), ('DISCUSSION_REPLY', '💭 Discussion Reply'), ('ACCOUNT_VERIFIED', '✅ Account Verified'), ('BADGE_EARNED', '🏆 Badge Earned'), ('MANUFACTURING_COMPLETE', '🏭 Manufacturing Complete'), ('QUALITY_CHECK_FAILED', '⚠️ Quality Check Failed'), ('ORDER_CONFIRMED', '✅ Order Confirmed'), ('ORDER_SHIPPED', '🚚 Order Shipped'), ('ORDER_DELIVERED', '📦 Order Delivered'), ('PAYMENT_PROCESSED', '💳 Payment Processed'), ('NEW_PRODUCT_RECOMMENDATION', '✨ New Product You May Like'), ('PRICE_DROP', '💰 Price Drop Alert'), ('BACK_IN_STOCK', '📦 Back in Stock'), ('NEW_PROJECT', '🌍 New Community Project'), ('WISHLIST_SALE', '🎉 Wishlist Item on Sale'), ('LOYALTY_REWARD', '🎁 Loyalty Reward Earned'), ('VENDOR_RESPONSE', '💬 Vendor Responded'), ('REVIEW_HELPFUL', '👍 Review Marked Helpful'), ('NEW_FOLLOWER', '👤 New Follower')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL to redirect when notification is clicked', max_length=500, null=True)),
                ('action_text', models.CharField(blank=True, help_text='Text for action button (e.g., "View Order")', max_length=100, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When notification should be auto-deleted', null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx'), models.Index(fields=['notification_type', 'recipient'], name='notificatio_notific_33c455_idx')],
            },
        ),
    ]
