# Generated by Django 4.2.25 on 2025-11-11 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_productreview_product_products_pr_price_ce096c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'CUSTOMER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='products.product')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['product', 'viewed_at'], name='products_pr_product_0c74ab_idx'), models.Index(fields=['customer', 'viewed_at'], name='products_pr_custome_532488_idx'), models.Index(fields=['session_key', 'viewed_at'], name='products_pr_session_4ade24_idx')],
            },
        ),
    ]
