# Generated by Django 4.2.25 on 2025-11-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_add_category_tags_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['tier', 'name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
